services:

  db:
    image: mongo:4.2.7-bionic
    networks:
      - backend
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mhub
      - MONGO_INITDB_ROOT_PASSWORD=uu9ieTh1
      # https://github.com/docker-library/mongo/issues/329
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    volumes:
      - db-data:/data/db
    command: [ "--bind_ip_all" ]

  server:
    image: ghcr.io/mapchete/mapchete:2026.2.0
    depends_on:
      - dask_scheduler
      - db
    environment:
      - MHUB_DASK_SCHEDULER_URL=tcp://dask_scheduler:8786
      - MHUB_MONGODB_URL=mongodb://mhub:uu9ieTh1@db:27017
    ports:
      - ${MHUB_PORT:-5000}:${MHUB_PORT:-5000}
    networks:
      - backend
      - frontend
    command:
      [
        "mhub-server",
        "start",
        "--host",
        "0.0.0.0",
        "--port",
        "${MHUB_PORT:-5000}",
        "--log-level",
        "debug"
      ]

  dask_scheduler:
    image: ghcr.io/mapchete/mapchete:2026.2.0
    networks:
      - backend
    command:
      [
        "dask", "scheduler",
        "--host",
        "dask_scheduler",
        "--port",
        "8786"
      ]

  dask_worker:
    image: ghcr.io/mapchete/mapchete:2026.2.0
    depends_on:
      - dask_scheduler
    networks:
      - backend
    command:
      [
        "dask", "worker",
        "--nthreads",
        "2",
        "--nworkers",
        "8",
        "tcp://dask_scheduler:8786"
      ]

volumes:
  db-data:

    null
networks:
  backend: null
  frontend: null
